os:
  - linux

language: node_js
node_js:
  - 17
install:
  - npm install -g apifox-cli
script:
  - apifox run apifox run http://192.168.10.208:5777/api/v1/projects/345286/api-test/ci-config/345136/detail?token=x9txg4nbJoKdVpWyBlnIjs -r html,cli
